[CmdletBinding()]
param([string] $Output = (Join-Path $PSScriptRoot '../../src/windows/AiUsage.Windows/Themes/Tokens.xaml'))
# Generates Themes/Tokens.xaml from the AIU-010 design tokens (Quiet Editorial 1b, specification section 3).
# The app has one appearance, the designed dark palette (D-182). Framework lightweight-styling keys take their colour from a token.
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# name = dark palette value
$tokens = [ordered]@{
    AppBg = '#1F1E1B'
    Card = '#282725'
    Card2 = '#31302C'
    Stroke = '#1FF3F1EC'
    Stroke2 = '#42F3F1EC'
    Text = '#F3F1EC'
    Text2 = '#B8B2A7'
    Text3 = '#8A857B'
    Accent = '#E38A6C'
    AccentHover = '#EEA38A'
    AccentText = '#1F1E1B'
    AccentSoft = '#2EE38A6C'
    Primary = '#F3F1EC'
    PrimaryText = '#1F1E1B'
    Fill = '#F3F1EC'
    OkFill = '#6CCB8A'
    WarnFill = '#F0A35E'
    Warn = '#F0A35E'
    WarnBg = '#24E5B95A'
    WarnStroke = '#73E5B95A'
    Crit = '#FF9C8A'
    CritBg = '#24FF9C8A'
    CritStroke = '#73FF9C8A'
    Ok = '#7BCB8A'
    Track = '#1FF3F1EC'
    Hatch = '#52F3F1EC'
    Skel = '#2C2B28'
    Skel2 = '#3A3834'
    Focus = '#F3F1EC'
    Btn = '#282725'
    BtnHover = '#33322E'
    DestructiveText = '#1F1E1B'
    Transparent = '#00000000'
}

# Framework key = token it takes its colour from.
$aliases = [ordered]@{
    ToggleSwitchFillOn = 'Accent'; ToggleSwitchFillOnPointerOver = 'AccentHover'; ToggleSwitchFillOnPressed = 'AccentHover'; ToggleSwitchKnobFillOn = 'AccentText'; ToggleSwitchKnobFillOnPointerOver = 'AccentText'; ToggleSwitchKnobFillOnPressed = 'AccentText'
    ToggleSwitchFillOff = 'Card2'; ToggleSwitchFillOffPointerOver = 'Card2'; ToggleSwitchStrokeOff = 'Stroke2'; ToggleSwitchStrokeOffPointerOver = 'Stroke2'; ToggleSwitchKnobFillOff = 'Text2'; ToggleSwitchKnobFillOffPointerOver = 'Text'
    ToggleSwitchContentForeground = 'Text'; ToggleSwitchHeaderForeground = 'Text'
    TextControlBackground = 'Card'; TextControlBackgroundPointerOver = 'Card'; TextControlBackgroundFocused = 'Card'; TextControlBorderBrush = 'Stroke2'; TextControlBorderBrushPointerOver = 'Text2'; TextControlBorderBrushFocused = 'Accent'
    TextControlForeground = 'Text'; TextControlForegroundPointerOver = 'Text'; TextControlForegroundFocused = 'Text'; TextControlPlaceholderForeground = 'Text3'; TextControlPlaceholderForegroundFocused = 'Text3'; TextControlPlaceholderForegroundPointerOver = 'Text3'
    TextControlSelectionHighlightColor = 'Accent'; TextControlHeaderForeground = 'Text2'
    ComboBoxBackground = 'Card'; ComboBoxBackgroundPointerOver = 'BtnHover'; ComboBoxBackgroundPressed = 'Card2'; ComboBoxBackgroundFocused = 'Card'; ComboBoxBorderBrush = 'Stroke2'; ComboBoxBorderBrushPointerOver = 'Text2'; ComboBoxBorderBrushFocused = 'Accent'
    ComboBoxForeground = 'Text'; ComboBoxForegroundFocused = 'Text'; ComboBoxPlaceHolderForeground = 'Text3'; ComboBoxDropDownGlyphForeground = 'Text2'; ComboBoxDropDownBackground = 'Card'; ComboBoxDropDownBorderBrush = 'Stroke2'; ComboBoxHeaderForeground = 'Text2'
    ComboBoxItemForeground = 'Text'; ComboBoxItemForegroundSelected = 'Text'; ComboBoxItemBackgroundSelected = 'AccentSoft'; ComboBoxItemBackgroundSelectedPointerOver = 'AccentSoft'; ComboBoxItemBackgroundPointerOver = 'Card2'; ComboBoxItemPillFillBrush = 'Accent'
    CheckBoxForegroundUnchecked = 'Text2'; CheckBoxForegroundChecked = 'Text2'; CheckBoxForegroundUncheckedPointerOver = 'Text'; CheckBoxForegroundCheckedPointerOver = 'Text'
    CheckBoxCheckBackgroundFillChecked = 'Accent'; CheckBoxCheckBackgroundFillCheckedPointerOver = 'AccentHover'; CheckBoxCheckBackgroundStrokeChecked = 'Accent'; CheckBoxCheckGlyphForegroundChecked = 'AccentText'; CheckBoxCheckGlyphForegroundCheckedPointerOver = 'AccentText'
    CheckBoxCheckBackgroundFillUnchecked = 'Card'; CheckBoxCheckBackgroundStrokeUnchecked = 'Stroke2'; CheckBoxCheckBackgroundStrokeUncheckedPointerOver = 'Text2'
    ContentDialogBackground = 'Card'; ContentDialogForeground = 'Text'; ContentDialogBorderBrush = 'Stroke2'; ContentDialogTopOverlay = 'Card'
    ProgressBarForeground = 'Accent'; ProgressBarBackground = 'Track'; ProgressRingForegroundThemeBrush = 'Accent'
    FlyoutPresenterBackground = 'Card'; FlyoutBorderThemeBrush = 'Stroke2'; MenuFlyoutPresenterBackground = 'Card'; MenuFlyoutPresenterBorderBrush = 'Stroke2'
    MenuFlyoutItemForeground = 'Text'; MenuFlyoutItemForegroundPointerOver = 'Text'; MenuFlyoutItemBackgroundPointerOver = 'Card2'; MenuFlyoutItemBackgroundPressed = 'Card2'; MenuFlyoutItemForegroundDisabled = 'Text3'
    ToolTipBackground = 'Card'; ToolTipForeground = 'Text'; ToolTipBorderBrush = 'Stroke2'
    SystemControlFocusVisualPrimaryBrush = 'Focus'; SystemControlFocusVisualSecondaryBrush = 'AppBg'
    ScrollViewerScrollBarSeparatorBackground = 'Transparent'
    RadioButtonsHeaderForeground = 'Text2'
}

$builder = New-Object Text.StringBuilder
[void]$builder.AppendLine('<!-- Generated by tools/windows/New-ThemeTokens.ps1 from the AIU-010 dark design tokens. Edit the script, not this file. -->')
[void]$builder.AppendLine('<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
foreach ($name in $tokens.Keys) { [void]$builder.AppendLine("  <SolidColorBrush x:Key=`"${name}Brush`" Color=`"$($tokens[$name])`" />") }
foreach ($alias in $aliases.Keys) { [void]$builder.AppendLine("  <SolidColorBrush x:Key=`"$alias`" Color=`"$($tokens[$aliases[$alias]])`" />") }
[void]$builder.AppendLine('</ResourceDictionary>')
[IO.File]::WriteAllText([IO.Path]::GetFullPath($Output), $builder.ToString(), (New-Object Text.UTF8Encoding($false)))
"Generated $($tokens.Count) tokens and $($aliases.Count) framework aliases."
